@url_dev=http://127.0.0.1:3052/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 93eb5513d14525b8181e46e158600df914fb472f155a13897e69c311ec9841cab5ea9c274c65e0b4ba64e5d9373e10b36a8cfa8865146aa943b039f51d3653ab

{
    "name": "Shop New",
    "email": "shop01@gmail.com",
    "password": "shop01"
}

### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: 93eb5513d14525b8181e46e158600df914fb472f155a13897e69c311ec9841cab5ea9c274c65e0b4ba64e5d9373e10b36a8cfa8865146aa943b039f51d3653ab

{
    "email": "shop01@gmail.com",
    "password": "shop01"
}

### logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: 93eb5513d14525b8181e46e158600df914fb472f155a13897e69c311ec9841cab5ea9c274c65e0b4ba64e5d9373e10b36a8cfa8865146aa943b039f51d3653ab
x-client-id: 65fdb2e576eadf6ff96e8eeb
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWZkYjJlNTc2ZWFkZjZmZjk2ZThlZWIiLCJlbWFpbCI6InNob3AwMUBnbWFpbC5jb20iLCJpYXQiOjE3MTEzMzQwNTcsImV4cCI6MTcxMTUwNjg1N30.NWWjyUuSnQ1MAgrNnxkKWMlh0XadFF0wDeyhwe7hu-M

### handle-refresh-token
POST {{url_dev}}/shop/handle-refresh-token
Content-Type: application/json
x-api-key: 93eb5513d14525b8181e46e158600df914fb472f155a13897e69c311ec9841cab5ea9c274c65e0b4ba64e5d9373e10b36a8cfa8865146aa943b039f51d3653ab
x-client-id: 65fdb2e576eadf6ff96e8eeb
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWZkYjJlNTc2ZWFkZjZmZjk2ZThlZWIiLCJlbWFpbCI6InNob3AwMUBnbWFpbC5jb20iLCJpYXQiOjE3MTEzNTk1NDYsImV4cCI6MTcxMTUzMjM0Nn0.bJ25jnfhxwlnn2eSWvZghfdde82mmewblW6yTQEFgNM
x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWZkYjJlNTc2ZWFkZjZmZjk2ZThlZWIiLCJlbWFpbCI6InNob3AwMUBnbWFpbC5jb20iLCJpYXQiOjE3MTEzNTk1NDYsImV4cCI6MTcxMTUzMjM0Nn0.fdq5_Gmv8W1_dp_YFgvHAMa9T585Hq-0lr4FZbzXtFA

# {
#     "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWZkYjJlNTc2ZWFkZjZmZjk2ZThlZWIiLCJlbWFpbCI6InNob3AwMUBnbWFpbC5jb20iLCJpYXQiOjE3MTEzMzQwNTcsImV4cCI6MTcxMTUwNjg1N30.7xdOBVCQsogyJX0duyCAtQvSdDJIfm29_XOucT39ptA"
# }

### create new product
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: 93eb5513d14525b8181e46e158600df914fb472f155a13897e69c311ec9841cab5ea9c274c65e0b4ba64e5d9373e10b36a8cfa8865146aa943b039f51d3653ab
x-client-id: 65fdb2e576eadf6ff96e8eeb
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWZkYjJlNTc2ZWFkZjZmZjk2ZThlZWIiLCJlbWFpbCI6InNob3AwMUBnbWFpbC5jb20iLCJpYXQiOjE3MTEzNjc5ODQsImV4cCI6MTcxMTU0MDc4NH0.tCgnwvSyJaefurDmmNpc2fQOvRt6cd6BlQDfYyLTjhU
x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWZkYjJlNTc2ZWFkZjZmZjk2ZThlZWIiLCJlbWFpbCI6InNob3AwMUBnbWFpbC5jb20iLCJpYXQiOjE3MTEzNjc5ODQsImV4cCI6MTcxMTU0MDc4NH0.Ok-HkDrjQlgcXNjXgPinhH1jUZJ90Yb2gSPQyTASm3I

{
    "product_name": "New Jeans",
    "product_description": "High-quality jeans",
    "product_price": 50,
    "product_shop": "65fdb2e576eadf6ff96e8eeb",
    "product_type": "Clothing",
    "product_thumb": "product_thumb",
    "product_quantity": 10,
    "product_attributes": {
        "brand": "Levi",
        "size": "L",
        "material": "Denim"
    }
}

### get drafts for shop
GET {{url_dev}}/product/drafts/all
Content-Type: application/json
x-api-key: 93eb5513d14525b8181e46e158600df914fb472f155a13897e69c311ec9841cab5ea9c274c65e0b4ba64e5d9373e10b36a8cfa8865146aa943b039f51d3653ab
x-client-id: 65fdb2e576eadf6ff96e8eeb
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWZkYjJlNTc2ZWFkZjZmZjk2ZThlZWIiLCJlbWFpbCI6InNob3AwMUBnbWFpbC5jb20iLCJpYXQiOjE3MTEzNjc5ODQsImV4cCI6MTcxMTU0MDc4NH0.tCgnwvSyJaefurDmmNpc2fQOvRt6cd6BlQDfYyLTjhU
x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWZkYjJlNTc2ZWFkZjZmZjk2ZThlZWIiLCJlbWFpbCI6InNob3AwMUBnbWFpbC5jb20iLCJpYXQiOjE3MTEzNjc5ODQsImV4cCI6MTcxMTU0MDc4NH0.Ok-HkDrjQlgcXNjXgPinhH1jUZJ90Yb2gSPQyTASm3I

### get published by shop
GET {{url_dev}}/product/published/all
Content-Type: application/json
x-api-key: 93eb5513d14525b8181e46e158600df914fb472f155a13897e69c311ec9841cab5ea9c274c65e0b4ba64e5d9373e10b36a8cfa8865146aa943b039f51d3653ab
x-client-id: 65fdb2e576eadf6ff96e8eeb
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWZkYjJlNTc2ZWFkZjZmZjk2ZThlZWIiLCJlbWFpbCI6InNob3AwMUBnbWFpbC5jb20iLCJpYXQiOjE3MTEzNjc5ODQsImV4cCI6MTcxMTU0MDc4NH0.tCgnwvSyJaefurDmmNpc2fQOvRt6cd6BlQDfYyLTjhU
x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWZkYjJlNTc2ZWFkZjZmZjk2ZThlZWIiLCJlbWFpbCI6InNob3AwMUBnbWFpbC5jb20iLCJpYXQiOjE3MTEzNjc5ODQsImV4cCI6MTcxMTU0MDc4NH0.Ok-HkDrjQlgcXNjXgPinhH1jUZJ90Yb2gSPQyTASm3I
